### PR TITLE
Add third party Dart client to the platform docs

### PR DESCRIPTION
**Pull request by KacperKluka**
This PR adds a Dart client to the platform docs under Third-Party Clients. It can be used in both pure Dart and Flutter applications.

Link to the official package repository page https://pub.dev/packages/mistralai_client_dart
Link to the Github page https://github.com/nomtek/mistralai_client_dart

This is the same PR as https://github.com/mistralai/platform-docs-public/pull/30 but I had to reopen it to fix merge conflicts.

### CODE REVIEW

**Review by hrjn — APPROVED** [review]
Thanks for the contribution 🙂

**Review by hrjn — CHANGES_REQUESTED** [review]
@KacperKluka I tried testing your client with one of the examples:
1. I installed Dart 
2. I cloned your repository
3. I ran `dart examples/mistralai_client_dart_example.dart` and got this error:

```
  open-mistral-7b, mistral-tiny-2312, mistral-tiny, open-mixtral-8x7b, open-mixtral-8x22b, open-mixtral-8x22b-2404, mistral-small-2312, mistral-small, mistral-small-2402, mistral-small-latest, mistral-medium-latest, mistral-medium-2312, mistral-medium, mistral-large-latest, mistral-large-2402, mistral-embed, ft:open-mistral-7b:587a6b29:20240514:7e773925, ft:open-mistral-7b:587a6b29:20240514:7b8f6053
Unhandled exception:
MistralAIClientException: Request POST https://api.mistral.ai/v1/chat/completions failed with status code: 422, body: {"object":"error","message":{"detail":[{"type":"extra_forbidden","loc":["body","messages",0,"user","name"],"msg":"Extra inputs are not permitted","input":null},{"type":"extra_forbidden","loc":["body","messages",0,"user","tool_calls"],"msg":"Extra inputs are not permitted","input":null}]},"type":"invalid_request_error","param":null,"code":null}
#0      _requestJson (package:mistralai_client_dart/src/network/request.dart:22:7)
<asynchronous suspension>
#1      main (file:///Users/harizo/Downloads/staging/mistralai_client_dart/example/mistralai_client_dart_example.dart:21:26)
<asynchronous suspension>
```

Looking at the code, the `client.listModels()` call was successful but the chat completion query is failing. Am I missing something? If so please do not hesitate to point it out (I am no Dart expert 🙂), once I get the example working I can approve and merge the PR. Thanks !

**Comment by gawi151** [comment]
Hi @hrjn,

I'm one of the maintainers of the Dart package. Since @KacperKluka is off this week, I'll answer your question.

Thanks a lot for checking it out 🙇‍♂️. You did everything right! It looks like the Mistral API changed how strict it is about sent fields. We're working on fixing it and I'll let you know as soon as it's sorted.

For now, let's keep this PR open until we get it resolved.

**Comment by gawi151** [comment]
@hrjn It should be now fixed in the repo of our package ;)

**Review by hrjn — APPROVED** [review]
I managed to run the examples with the latest updates on your repo, thanks for the fix 🙂

**Pull request merged**
