### PR TITLE
Portkey open source Gateway integration with Codestral

### PR DESCRIPTION
**Pull request by vrushankportkey**
Portkey natively integrates with Codestral Instruct on both the`codestral.mistral` and `api.mistral` URLs. Have showcased the `api.mistral` example here, and added the `codestral.mistral` example in the attached doc.

Portkey will give out-of-the-box observability over all Codestral requests and also help make the requests robust & reliable with features like fallbacks, load balancing, and more.

### CODE REVIEW

**Review by sophiamyang — APPROVED** [review]

**Comment by sophiamyang** [comment]
Hi @vrushankportkey, there is a conflict with the updated doc. Could you help resolve the conflict first? Thanks!

**Comment by vrushankportkey** [comment]
@sophiamyang done!

**Comment by vrushankportkey** [comment]
@sophiamyang just checking in :)

**Comment by sophiamyang** [comment]
Hi @vrushankportkey, I think Portkey might be more relevant if we have an observability section in the future. Will you keep you updated. In the meantime, we'd love to move forward with Portkey cookbook. Could you update this PR: https://github.com/mistralai/cookbook/pull/33 from Portkey? Thanks!

**Pull request closed without merging**
